### ISSUE TITLE
ToDo im Vorhaben kann nicht gespeichert werden

### ISSUE THREAD

**Issue by SophiaHintze** [Estate-of-the-Art/finance-estate-issues#17]
### Eingeloggter Benutzer

sophia.hintze@xcapital.de

### Betroffene Resource

0191f918-88a4-73e9-8cc1-ed0431663eea?activeRelationManager=1

### Panels/ Team-Typ

- [ ] Admin
- [ ] Bank
- [ ] Customer (Kunde)
- [ ] Immo (Bauträger)
- [ ] Makler
- [ ] Sales (Immobilienvertrieb)
- [X] Xcapital (Finanzierungsabteilung)

### Beschreibung

Ich kann kein ToDo speichern in einem Vorhaben

### Erwartetes Verhalten

Speichern

### Wiederholt sich dieser Fehler?

Auch bei anderen Vorhaben

### Operating System

- [ ] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [ ] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [ ] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [ ] den Fehler auf anderen Panels überprüft
- [ ] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

### Bilder/Screenshots/Mockups/Links?

<img width="1442" alt="Bildschirmfoto 2024-09-17 um 11 41 34" src="https://github.com/user-attachments/assets/fc7b90e8-bf2a-416d-ae8f-8e2d7e3c182c">

**Comment by john-wink** [comment]
Ich kann das lokal nicht reproduzieren. Kannst du genau die Schritte beschreiben was du gemacht hast?

**Comment by SophiaHintze** [comment]
Hallo, der Fehler tritt nicht mehr auf. Ich wollte im Vorhaben ein To-Do erstellen, doch als ich auf "Speichern" geklickt habe, passierte nichts. Ich habe daraufhin zweimal geklickt und bin anschließend in ein Meeting gegangen. Nach einer Stunde, als das Meeting vorbei war, funktionierte das System kurzzeitig nicht. Nachdem ich die Seite aktualisiert hatte und das System wieder lief, war das To-Do plötzlich zweimal im Vorhaben zu finden. Es hatte also doch funktioniert, allerdings ohne direkte Rückmeldung, abgesehen von einem schwarzen Bildschirm.
