### ISSUE TITLE
ToDo Board kann nicht geöffnet werden

### ISSUE THREAD

**Issue by SophiaHintze** [Estate-of-the-Art/finance-estate-issues#18]
### Eingeloggter Benutzer

sophia.hintze@xcapital.de

### Betroffene Resource

x-capital-gmbh/notifications-page

### Panels/ Team-Typ

- [ ] Admin
- [ ] Bank
- [ ] Customer (Kunde)
- [ ] Immo (Bauträger)
- [ ] Makler
- [ ] Sales (Immobilienvertrieb)
- [X] Xcapital (Finanzierungsabteilung)

### Beschreibung

ToDo Board kann nicht geöffnet werden. Wenn ich auf ToDo Board klicke kommt "Interner Fehler"

### Erwartetes Verhalten

Das ToDo Board öffnet sich 

### Wiederholt sich dieser Fehler?

Des Öfteren versucht

### Operating System

- [ ] Windows
- [X] Apple
- [ ] ChromeOS
- [ ] Linux

### Browser

- [ ] Google Chrome
- [X] Microsoft Edge
- [ ] Safari
- [ ] Mozilla Firefox
- [ ] Samsung Internet
- [ ] Opera

### Ich habe ...

- [ ] den Fehler auf anderen Panels überprüft
- [ ] den Fehler auf anderen Betriebssystemen (OS) überprüft
- [X] den Fehler in anderen Browser reproduziert

### Existiert bereits eine ähnliche/gleiche Fehlermeldung?

- [X] Ich habe die bisherigen Fehlermeldungen überprüft und nichts vergleichbares gefunden

### Bilder/Screenshots/Mockups/Links?

<img width="908" alt="Bildschirmfoto 2024-09-21 um 11 34 32" src="https://github.com/user-attachments/assets/84f9b7b0-d358-4cdb-a0d3-23c657f8f6ab">
